spring.application.name=InternalManagementSystem

spring.datasource.username=root
spring.datasource.password=Saurabh@990
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create